branch-defaults:
  stable:
    environment: CoreBackend-env
environment-defaults:
  CoreBackend-env:
    branch: null
    repository: null
  CoreBackend-env-1:
    branch: null
    repository: null
global:
  application_name: Core-Backend
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:eu-north-1::platform/Python 3.7 running
    on 64bit Amazon Linux 2/3.0.0
  default_region: eu-north-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
